### ISSUE TITLE
Replace v.db.select with db.select where appropriate

### ISSUE THREAD

**Issue by benducke** [benducke/Network-reconstruction-tools-for-GRASS-GIS#62]
Replacing this:
`VAL=`v.db.select map="${input}" layer="1" columns="${field_name}" where="${condition}" -c --quiet``

With this:
`VAL=`db.select database="${atts_db}" sql="SELECT ${field_name} FROM ${input} WHERE ${condition};" -c --quiet``

... will give a speed-up of almost 60% for minimal refactoring effort!

**Comment by benducke** [comment]
This is appropriate, if:
* v.db.select is called in a loop
* v.db.select is used to query only a single value

**Comment by neteler** [comment]
Not sure if this hint is helpful (and it requires a SQLite/PG/MySQL backend): encapsulating SQL statements into a `TRANSACTION` notably speeds up the SQL backend processing:

```
BEGIN TRANSACTION
...
<SQL commands here>
....
END TRANSACTION
```

Python example:
- https://github.com/OSGeo/grass-addons/blob/02330febc0f50cb2fd28c40043701280536b53e1/src/vector/v.db.pyupdate/v.db.pyupdate.py#L129
- https://github.com/OSGeo/grass-addons/blob/grass8/src/vector/v.db.pyupdate/v.db.pyupdate.py#L189

Shell example:
- https://github.com/OSGeo/grass-legacy/blob/develbranch_6/scripts/db.dropcol/db.dropcol#L133
- https://github.com/OSGeo/grass-legacy/blob/2734c86fd5cb976b4a94b04a2cdc75b4613f6a77/scripts/db.dropcol/db.dropcol#L140

**Comment by benducke** [comment]
Thanks! I completely forgot about SQL transactions.
This gives a nice speed-up, especially when collating SQL statements before feeding them to the DBMS.

**Comment by benducke** [comment]
The use of v.db.select is also very common in all models support by v.net.models: These commonly reduce network connections by querying some sort of link attributes first.
